# Generated by Django 4.2.5 on 2023-09-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='tel',
        ),
    ]
